/**
 * Farmers Market Seed
 */


var farmersmarketSeed = [
  {
    "name": "Akebono Farmers' Market",
    "streetAddress": "",
    "locationInfo": "Akebono Parking Lot",
    "latitude": 19.49469006600043,
    "longitude": -154.94809898999975,
    "island": "Hawaii",
    "city": "Pahoa",
    "zipcode": "",
    "contact": "Vinton",
    "phone": "(808) 965-9205",
    "email": "",
    "website": ""
  },
  {
    "name": "Ala Moana Farmers' Market",
    "streetAddress": "1450 Ala Moana Blvd.",
    "locationInfo": "Ala Moana Center, upper deck by Sears, corner of Piikoi & Ala Moana Blvd.",
    "latitude": 21.28928015800045,
    "longitude": -157.84219969299974,
    "island": "Oahu",
    "city": "Honolulu",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 388-9696",
    "email": "AlaMoanaFarmersMarket@gmail.com",
    "website": "http://alamoanafarmersmarket.com/ala-moana.html"
  },
  {
    "name": "Alii Garden Market Place",
    "streetAddress": "75-6129 Alii Drive",
    "locationInfo": "",
    "latitude": 19.61399064100044,
    "longitude": -155.98165889099974,
    "island": "Hawaii",
    "city": "Kailua-Kona",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 334-1381",
    "email": "",
    "website": ""
  },
  {
    "name": "Banyan Court Mall (People's Open Market)",
    "streetAddress": "800 North King Street",
    "locationInfo": "",
    "latitude": 21.302690421000477,
    "longitude": -157.85208973299973,
    "island": "Oahu",
    "city": "Honolulu",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 522-7088",
    "email": "",
    "website": ""
  },
  {
    "name": "Benjamin Parker Elementary School",
    "streetAddress": "45-259 Waikalua Road",
    "locationInfo": "",
    "latitude": 21.413500808000435,
    "longitude": -157.79883930699975,
    "island": "Oahu",
    "city": "Kaneohe",
    "zipcode": "",
    "contact": "Sonny Doung",
    "phone": "(808) 225-4002",
    "email": "sonnydoung@hotmail.com",
    "website": ""
  },
  {
    "name": "City Hall Parking Lot Deck (People's Open Market)",
    "streetAddress": "",
    "locationInfo": "Alapai & Beretania Street",
    "latitude": 21.304850435000446,
    "longitude": -157.85774940299973,
    "island": "Oahu",
    "city": "Honolulu",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 522-7088",
    "email": "",
    "website": ""
  },
  {
    "name": "Country Market & Craft Fair at Waimanalo Homestead Community Center",
    "streetAddress": "1330 Kalanianaole Hwy.\nHI",
    "locationInfo": "Waimanalo Homestead Community Center",
    "latitude": "",
    "longitude": "",
    "island": "Oahu",
    "city": "Waimanalo",
    "zipcode": "",
    "contact": "Paul Richard",
    "phone": "(808) 259-8611",
    "email": "",
    "website": ""
  },
  {
    "name": "Davies Pacific Center",
    "streetAddress": "841 Bishop Street",
    "locationInfo": "*2nd & 4th Tuesdays",
    "latitude": 21.307830753000474,
    "longitude": -157.86242916299975,
    "island": "Oahu",
    "city": "Honolulu",
    "zipcode": "",
    "contact": "",
    "phone": "",
    "email": "",
    "website": ""
  },
  {
    "name": "Dole Cannery",
    "streetAddress": "650 Iwilei Road",
    "locationInfo": "",
    "latitude": 21.316240109000432,
    "longitude": -157.87050896699975,
    "island": "Oahu",
    "city": "Honolulu",
    "zipcode": "",
    "contact": "Doreen Rozemond",
    "phone": "",
    "email": "drozemond@castlecooke.com",
    "website": ""
  },
  {
    "name": "Ewa Beach Community Park (People's Open Market)",
    "streetAddress": "91-955 North Road",
    "locationInfo": "",
    "latitude": 21.31354031200044,
    "longitude": -158.00906976999974,
    "island": "Oahu",
    "city": "Ewa Beach",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 522-7088",
    "email": "",
    "website": "www.co.honolulu.hi.us/parks/programs/pom"
  },
  {
    "name": "Ewa Beach Elementary School",
    "streetAddress": "91-740 Papipi Road",
    "locationInfo": "",
    "latitude": 21.31503419100045,
    "longitude": -158.01439823499973,
    "island": "Oahu",
    "city": "Ewa Beach",
    "zipcode": "",
    "contact": "Sonny Doung",
    "phone": "(808) 225-4002",
    "email": "sonnydoung@hotmail.com",
    "website": "http://www.mahikufarmersmarket.com"
  },
  {
    "name": "Ewa Beach Elementary School",
    "streetAddress": "91-740 Papipi Road",
    "locationInfo": "",
    "latitude": "",
    "longitude": "",
    "island": "Oahu",
    "city": "Ewa Beach",
    "zipcode": 96706,
    "contact": "Sonny Doung",
    "phone": "(808) 225-4002",
    "email": "sonnydoung@hotmail.com",
    "website": "www.mahikufarmersmarket.com"
  },
  {
    "name": "Farmers' Market of Maui-Honokowai",
    "streetAddress": "3636 Lower Honoapi'ilani Road",
    "locationInfo": "Location at Hawaiian Motors parking lot (across from Honokowai Park)",
    "latitude": 20.917090441000425,
    "longitude": -156.68139921299974,
    "island": "Maui",
    "city": "Lahina",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 669-7004",
    "email": "",
    "website": ""
  },
  {
    "name": "Farmers' Market of Maui-Kihei",
    "streetAddress": "61 South Kihei Road",
    "locationInfo": "Located in Suda Store parking lot on South Kihei Road",
    "latitude": 20.781950970000423,
    "longitude": -156.46301909199974,
    "island": "Maui",
    "city": "Kihei",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 875-0949",
    "email": "",
    "website": ""
  },
  {
    "name": "Fern Forest Town Market",
    "streetAddress": "",
    "locationInfo": "",
    "latitude": "",
    "longitude": "",
    "island": "Hawaii",
    "city": "Fern Forest",
    "zipcode": "",
    "contact": "Jan",
    "phone": "(808) 968-8631",
    "email": "",
    "website": ""
  },
  {
    "name": "First Insurance Center",
    "streetAddress": "1100 Ward Ave",
    "locationInfo": "*1st & 3rd Wednesdays, across from Thomas Square",
    "latitude": 21.30303034500048,
    "longitude": -157.84976903599974,
    "island": "Oahu",
    "city": "Honolulu",
    "zipcode": "",
    "contact": "",
    "phone": "",
    "email": "",
    "website": ""
  },
  {
    "name": "First Insurance Center",
    "streetAddress": "1100 Ward Ave.",
    "locationInfo": "Across from Thomas Square",
    "latitude": "",
    "longitude": "",
    "island": "Oahu",
    "city": "Honolulu",
    "zipcode": "",
    "contact": "",
    "phone": "",
    "email": "",
    "website": ""
  },
  {
    "name": "Fort Street near Wilcox Park",
    "streetAddress": "",
    "locationInfo": "In front of Macy's",
    "latitude": 21.304850435000446,
    "longitude": -157.85774940299973,
    "island": "Oahu",
    "city": "Honolulu",
    "zipcode": "",
    "contact": "Lori Zane",
    "phone": "(808) 777-9216",
    "email": "",
    "website": "http://www.local-farmers-markets.com/market/1162/honolulu/fort-street-near-wilcox-park"
  },
  {
    "name": "Fort Street near Wilcox Park",
    "streetAddress": "",
    "locationInfo": "Honolulu (In front of Macy's)",
    "latitude": "",
    "longitude": "",
    "island": "Oahu",
    "city": "Honolulu",
    "zipcode": "",
    "contact": "Lori Zane",
    "phone": "(808) 777-9216",
    "email": "",
    "website": "www.local-farmers-markets.com/market/1162/honolulu/fort-street-near-wilcox-park"
  },
  {
    "name": "Halawa District Park (People's Open Market)",
    "streetAddress": "99-795 Iwaiwa Street\nHI",
    "locationInfo": "",
    "latitude": "",
    "longitude": "",
    "island": "Oahu",
    "city": "",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 522-7088",
    "email": "",
    "website": ""
  },
  {
    "name": "Halawa District Park (People's Open Market)",
    "streetAddress": "99-795 Iwaiwa Street",
    "locationInfo": "",
    "latitude": "",
    "longitude": "",
    "island": "Oahu",
    "city": "Honolulu",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 522-7088",
    "email": "",
    "website": "www.co.honolulu.hi.us/parks/programs/pom"
  },
  {
    "name": "Hale'iwa Farmers' Market",
    "streetAddress": "",
    "locationInfo": "Kam Hwy. and Joseph P. Leong Bypass",
    "latitude": 21.304850435000446,
    "longitude": -157.85774940299973,
    "island": "Oahu",
    "city": "Haleiwa",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 388-9696",
    "email": "haleiwafarmersmarket@gmail.com",
    "website": "http://www.haleiwafarmersmarket.com"
  },
  {
    "name": "Hale'iwa Farmers' Market",
    "streetAddress": "59-864 Kamehameha Hwy",
    "locationInfo": "Kam Hwy. and Joseph P. Leong Bypass",
    "latitude": "",
    "longitude": "",
    "island": "Oahu",
    "city": "Haleiwa",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 388-9696",
    "email": "haleiwafarmersmarket@gmail.com",
    "website": "www.haleiwafarmersmarket.com"
  },
  {
    "name": "Hali'imaile Farmers' Market",
    "streetAddress": "900 Haliimaile Rd",
    "locationInfo": "In former Maui Pineapple Co. parking lot next to Hali'imaile General Store",
    "latitude": 20.868329790000473,
    "longitude": -156.34021118699974,
    "island": "Maui",
    "city": "Makawao",
    "zipcode": 96768,
    "contact": "",
    "phone": "(808) 463-1676",
    "email": "",
    "website": ""
  },
  {
    "name": "Hana Fresh Market",
    "streetAddress": "4590 Hana Highway",
    "locationInfo": "between mile markers 34 and 35.",
    "latitude": 20.64924257700045,
    "longitude": -156.06698936499973,
    "island": "Maui",
    "city": "Hana",
    "zipcode": 96713,
    "contact": "",
    "phone": "(808) 248-7515",
    "email": "",
    "website": ""
  },
  {
    "name": "Hanalei Saturday Market",
    "streetAddress": "",
    "locationInfo": "",
    "latitude": 22.201686187000462,
    "longitude": -159.50311687099975,
    "island": "Kauai",
    "city": "Hanalei",
    "zipcode": "",
    "contact": "Stephanie Struble",
    "phone": "(808) 826-1011",
    "email": "",
    "website": "http://www.halehalawai.org/market.htm"
  },
  {
    "name": "Hanapepe Park (Sunshine Markets)",
    "streetAddress": "",
    "locationInfo": "Old Hanapepe Town",
    "latitude": "",
    "longitude": "",
    "island": "Kauai",
    "city": "",
    "zipcode": "",
    "contact": "Cora Asuncion",
    "phone": "(808) 742-1834",
    "email": "",
    "website": ""
  },
  {
    "name": "Hawaii Kai Farmers' Market",
    "streetAddress": "511 Lunalilo Home Road",
    "locationInfo": "Kaiser High School parking lot",
    "latitude": 21.286071053000455,
    "longitude": -157.69769887499973,
    "island": "Oahu",
    "city": "Honolulu",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 388-9696",
    "email": "",
    "website": "http://www.makekeomaunalua.com"
  },
  {
    "name": "Hawaii Kai Park-n-Ride (People's Open Market)",
    "streetAddress": "300 Keahole Street",
    "locationInfo": "",
    "latitude": 21.284702499000446,
    "longitude": -157.71043000699973,
    "island": "Oahu",
    "city": "Honolulu",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 522-7088",
    "email": "",
    "website": ""
  },
  {
    "name": "Hawaii Kai Towne Center",
    "streetAddress": "333 Keahole Street",
    "locationInfo": "Kalanianaole Highway at Keahole Street Behind Panda Express",
    "latitude": 21.28424007500047,
    "longitude": -157.71158963799974,
    "island": "Oahu",
    "city": "Honolulu",
    "zipcode": 96825,
    "contact": "",
    "phone": "(808) 396-0766",
    "email": "",
    "website": ""
  },
  {
    "name": "Hawaiian Farmers of Hanalei",
    "streetAddress": "",
    "locationInfo": "Waipa",
    "latitude": "",
    "longitude": "",
    "island": "Kauai",
    "city": "Hanalei",
    "zipcode": "",
    "contact": "",
    "phone": "",
    "email": "",
    "website": ""
  },
  {
    "name": "Hawaiian Homestead Farmers' Market",
    "streetAddress": "64-759 Kahilu Road",
    "locationInfo": "Located at Kuhio Hale Building",
    "latitude": "",
    "longitude": "",
    "island": "Hawaii",
    "city": "Waimea",
    "zipcode": "",
    "contact": "",
    "phone": "",
    "email": "",
    "website": ""
  },
  {
    "name": "Hilo Coffee Mill \"Market @ The Mill",
    "streetAddress": "17-995 Volcano Rd",
    "locationInfo": "Hilo Coffee Mill Farm, Between Mile Markers 12 & 13",
    "latitude": "",
    "longitude": "",
    "island": "Hawaii",
    "city": "Hilo",
    "zipcode": "",
    "contact": "Katherine Patton",
    "phone": "(808) 968-1333",
    "email": "",
    "website": ""
  },
  {
    "name": "Hilo's Farmer's Market",
    "streetAddress": "",
    "locationInfo": "Corner of Kamehameha Avenue and Mamo Street",
    "latitude": "",
    "longitude": "",
    "island": "Hawaii",
    "city": "Hilo",
    "zipcode": "",
    "contact": "Keith",
    "phone": "(808) 933-1000",
    "email": "",
    "website": "www.hilofarmersmarket.com"
  },
  {
    "name": "Ho'oulu Community Farmers Market",
    "streetAddress": "",
    "locationInfo": "Keauhou Beach Resort Royal Gardens",
    "latitude": "",
    "longitude": "",
    "island": "Hawaii",
    "city": "Kailua-Kona",
    "zipcode": "",
    "contact": "Kumu Keala Ching",
    "phone": "(808) 324-2540",
    "email": "keala.ching@outrigger.com",
    "website": ""
  },
  {
    "name": "Honokaa Farmer's Market",
    "streetAddress": "",
    "locationInfo": "Old Botelho Bldg., Downtown Honokaa",
    "latitude": "",
    "longitude": "",
    "island": "Hawaii",
    "city": "Honokaa",
    "zipcode": "",
    "contact": "",
    "phone": "",
    "email": "",
    "website": ""
  },
  {
    "name": "Honolulu Farmers' Market at Neal S. Blaisdell Center",
    "streetAddress": "777 Ward Ave",
    "locationInfo": "Ward Ave. & King Street",
    "latitude": 21.29999544000043,
    "longitude": -157.85177574799974,
    "island": "Oahu",
    "city": "Honolulu",
    "zipcode": 96814,
    "contact": "",
    "phone": "(808) 848-2074",
    "email": "",
    "website": "http://www.hfbf.org"
  },
  {
    "name": "International Market Place",
    "streetAddress": "2330 Kalakaua Avenue",
    "locationInfo": "Next to Food Court",
    "latitude": 21.277500376000432,
    "longitude": -157.82711977399973,
    "island": "Oahu",
    "city": "Honolulu",
    "zipcode": "",
    "contact": "",
    "phone": "",
    "email": "",
    "website": ""
  },
  {
    "name": "Ka'u Farmers' Market",
    "streetAddress": "",
    "locationInfo": "In Front of Ace Hardware",
    "latitude": "",
    "longitude": "",
    "island": "Hawaii",
    "city": "Ka'u",
    "zipcode": "",
    "contact": "Dennis & Marge",
    "phone": "(808) 929-7239",
    "email": "dewell@hawaii.rr.com",
    "website": ""
  },
  {
    "name": "Kahaluu Farmers' Market",
    "streetAddress": "47-528A Kamehameha Hwy.",
    "locationInfo": "Windward Baptist Church (Across from 7-11)",
    "latitude": "",
    "longitude": "",
    "island": "Oahu",
    "city": "Kaneohe",
    "zipcode": "",
    "contact": "Sonny Doung",
    "phone": "(808) 225-4002",
    "email": "sonnydoung@hotmail.com",
    "website": "www.mahikufarmersmarket.com"
  },
  {
    "name": "Kailua District Park (People's Open Market)",
    "streetAddress": "21 South Kainalu Drive",
    "locationInfo": "",
    "latitude": 21.39584092800044,
    "longitude": -157.73751944899973,
    "island": "Oahu",
    "city": "Kailua",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 522-7088",
    "email": "",
    "website": ""
  },
  {
    "name": "Kailua Elementary School",
    "streetAddress": "315 Kuulei Road",
    "locationInfo": "Parking Lot",
    "latitude": "",
    "longitude": "",
    "island": "Oahu",
    "city": "Kailua",
    "zipcode": "",
    "contact": "Sonny Doung",
    "phone": "(808) 225-4002",
    "email": "sonnydoung@hotmail.com",
    "website": "www.mahikufarmersmarket.com"
  },
  {
    "name": "Kaka'ako Makai Community Cultural Marketplace",
    "streetAddress": "",
    "locationInfo": "One block makai of Ala Moana Blvd. & Ward Ave. corner Ilalo & Ahui Sts.",
    "latitude": 21.304850435000446,
    "longitude": -157.85774940299973,
    "island": "Oahu",
    "city": "Honolulu",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 330-6224",
    "email": "",
    "website": "http://www.KakaakoMakaiMarket.com"
  },
  {
    "name": "Kalaheo Neighborhood Center (Sunshine Markets)",
    "streetAddress": "",
    "locationInfo": "Papalina Road off Kaumualii, Kalaheo",
    "latitude": 21.90751165800043,
    "longitude": -159.51190744899975,
    "island": "Kauai",
    "city": "Kalaheo",
    "zipcode": "",
    "contact": "Matilda Adams at the site",
    "phone": "",
    "email": "",
    "website": ""
  },
  {
    "name": "Kalihi Farmers' Market at Kapalama Elementary School",
    "streetAddress": "1601 N. School Street",
    "locationInfo": "Kapalama Elementary School",
    "latitude": 21.335250464000467,
    "longitude": -157.86880934999974,
    "island": "Oahu",
    "city": "Honolulu",
    "zipcode": "",
    "contact": "Sonny Doung",
    "phone": "(808) 225-4002",
    "email": "sonnydoung@hotmail.com",
    "website": "http://www.mahikufarmersmarket.com"
  },
  {
    "name": "Kalihi Valley District Park (People's Open Market)",
    "streetAddress": "1911 Kam IV Road",
    "locationInfo": "",
    "latitude": 21.304850435000446,
    "longitude": -157.85774940299973,
    "island": "Oahu",
    "city": "Honolulu",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 522-7088",
    "email": "",
    "website": ""
  },
  {
    "name": "Kaneohe District Park (People's Open Market)",
    "streetAddress": "45-660 Keaahala Road",
    "locationInfo": "",
    "latitude": 21.409360657000434,
    "longitude": -157.81028953799975,
    "island": "Oahu",
    "city": "Kaneohe",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 522-7088",
    "email": "",
    "website": ""
  },
  {
    "name": "Kapaa New Town Park (Sunshine Markets)",
    "streetAddress": "",
    "locationInfo": "Kahau Road, Kapaa",
    "latitude": "",
    "longitude": "",
    "island": "Kauai",
    "city": "Kapaa",
    "zipcode": "",
    "contact": "Nancy Blalock",
    "phone": "",
    "email": "",
    "website": ""
  },
  {
    "name": "Kapolei Community Park (People's Open Market)",
    "streetAddress": "91-1049 Kamaaha Loop",
    "locationInfo": "",
    "latitude": 21.333890771000426,
    "longitude": -158.06702957399975,
    "island": "Oahu",
    "city": "Kapolei",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 522-7088",
    "email": "",
    "website": ""
  },
  {
    "name": "Kauai Community Market (Kauai Community College)",
    "streetAddress": "",
    "locationInfo": "Campus front parking lot across from Grove Farm",
    "latitude": "",
    "longitude": "",
    "island": "Kauai",
    "city": "Lihue",
    "zipcode": "",
    "contact": "Melissa McFerrin",
    "phone": "(808) 337-9944",
    "email": "kcfb@hawaiiantel.net",
    "website": ""
  },
  {
    "name": "Kaumualii Street (People's Open Market)",
    "streetAddress": "",
    "locationInfo": "Kalihi Street",
    "latitude": 21.304850435000446,
    "longitude": -157.85774940299973,
    "island": "Oahu",
    "city": "Honolulu",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 522-7088",
    "email": "",
    "website": ""
  },
  {
    "name": "Keaau Village Farmers' Market",
    "streetAddress": "16-0550 Old Volcano Road",
    "locationInfo": "",
    "latitude": "",
    "longitude": "",
    "island": "Hawaii",
    "city": "Keaau",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 966-4853",
    "email": "",
    "website": ""
  },
  {
    "name": "Keauhou Farmer's Market",
    "streetAddress": "",
    "locationInfo": "Keauhou Shopping Center, fronting Ace Hardware",
    "latitude": "",
    "longitude": "",
    "island": "Hawaii",
    "city": "Kailua-Kona",
    "zipcode": "",
    "contact": "Nancy",
    "phone": "(808) 322-3118",
    "email": "nkona@hawaii.rr.com",
    "website": ""
  },
  {
    "name": "Kekaha Neighborhood Center (Sunshine Markets)",
    "streetAddress": "",
    "locationInfo": "Elepaio Road, Kekaha",
    "latitude": "",
    "longitude": "",
    "island": "Kauai",
    "city": "Kekaha",
    "zipcode": "",
    "contact": "Cora Asuncion",
    "phone": "(808) 742-1834",
    "email": "",
    "website": ""
  },
  {
    "name": "Kekela Farm",
    "streetAddress": "64-604 Mana Road",
    "locationInfo": "",
    "latitude": "",
    "longitude": "",
    "island": "Hawaii",
    "city": "Waimea",
    "zipcode": 96743,
    "contact": "",
    "phone": "(808) 887-0023",
    "email": "",
    "website": ""
  },
  {
    "name": "Kilauea Neighborhood Center (Sunshine Markets)",
    "streetAddress": "",
    "locationInfo": "Keneke off Lighthouse Road, Kilauea",
    "latitude": "",
    "longitude": "",
    "island": "Kauai",
    "city": "Kilauea",
    "zipcode": 96754,
    "contact": "Ben Ferris",
    "phone": "(808) 822-1712",
    "email": "",
    "website": ""
  },
  {
    "name": "King's Village Shopping Center",
    "streetAddress": "131 Kaiulani Ave.",
    "locationInfo": "",
    "latitude": 21.27717082300046,
    "longitude": -157.82522887899975,
    "island": "Oahu",
    "city": "Honolulu",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 237-6340",
    "email": "",
    "website": "http://www.kings-village.com"
  },
  {
    "name": "Kinoole Farmer's Market",
    "streetAddress": "1990 Kinoole Street",
    "locationInfo": "",
    "latitude": 19.690021148000426,
    "longitude": -155.06952407299974,
    "island": "Hawaii",
    "city": "Hilo",
    "zipcode": "",
    "contact": "Lori",
    "phone": "(808) 557-2780",
    "email": "bifb@hawaiiantel.net",
    "website": ""
  },
  {
    "name": "Koloa Ball Park (Knudsen) (Sunshine Markets)",
    "streetAddress": "",
    "locationInfo": "Maluhia Road, Koloa",
    "latitude": "",
    "longitude": "",
    "island": "Kauai",
    "city": "Koloa",
    "zipcode": 96756,
    "contact": "Branch Harmony",
    "phone": "(808) 322-0718",
    "email": "",
    "website": ""
  },
  {
    "name": "Kona Farmers' Market",
    "streetAddress": "74-5465 Kamakaeha Avenue",
    "locationInfo": "Makapua Center - In front of K-Mart",
    "latitude": "",
    "longitude": "",
    "island": "Hawaii",
    "city": "Kailua-Kona",
    "zipcode": "",
    "contact": "Bob Gagne",
    "phone": "(808) 333-2478",
    "email": "gagner001@hawaii.rr.com",
    "website": ""
  },
  {
    "name": "Kukui Grove Shopping Center",
    "streetAddress": "",
    "locationInfo": "Lihue",
    "latitude": 21.978857825000432,
    "longitude": -159.36718896099975,
    "island": "Kauai",
    "city": "Lihue",
    "zipcode": "",
    "contact": "",
    "phone": "",
    "email": "",
    "website": ""
  },
  {
    "name": "Laupahoehoe Farmers' Market",
    "streetAddress": "",
    "locationInfo": "Laupahoehoe - next to the Minit Stop on Hwy. 19",
    "latitude": "",
    "longitude": "",
    "island": "Hawaii",
    "city": "Laupahoehoe",
    "zipcode": 96764,
    "contact": "Beth Fulton",
    "phone": "(808) 443-1679",
    "email": "bethflo@hotmail.com",
    "website": ""
  },
  {
    "name": "Lipoa Street Farmers' Market",
    "streetAddress": "95 Lipoa Street",
    "locationInfo": "",
    "latitude": 20.747920615000453,
    "longitude": -156.45249990599973,
    "island": "Maui",
    "city": "Kihei",
    "zipcode": 96753,
    "contact": "",
    "phone": "",
    "email": "",
    "website": ""
  },
  {
    "name": "Mahiku Farmers' Market (International Market Place)",
    "streetAddress": "",
    "locationInfo": "International Market Place-Waikiki (near the Food Court)",
    "latitude": "",
    "longitude": "",
    "island": "Oahu",
    "city": "",
    "zipcode": "",
    "contact": "Sonny Doung",
    "phone": "(808) 225-4002",
    "email": "sonnydoung@hotmail.com",
    "website": "www.mahikufarmersmarket.com"
  },
  {
    "name": "Mahiku Farmers' Market (Momilani Community Center)",
    "streetAddress": "715 Hoomoana St.",
    "locationInfo": "Corner of Hoomoana & Komo Mai Dr.",
    "latitude": "",
    "longitude": "",
    "island": "Oahu",
    "city": "Pearl City",
    "zipcode": "",
    "contact": "Sonny Doung",
    "phone": "(808) 225-4002",
    "email": "sonnydoung@hotmail.com",
    "website": "www.mahikufarmersmarket.com"
  },
  {
    "name": "Mahiku Farmers' Market at International Market Place-Waikiki",
    "streetAddress": "",
    "locationInfo": "International Market Place-Waikiki (near the Food Court)",
    "latitude": 21.3048504350004,
    "longitude": -157.857749402999,
    "island": "Oahu",
    "city": "Honolulu",
    "zipcode": "",
    "contact": "Sonny Doung",
    "phone": "(808) 225-4002",
    "email": "sonnydoung@hotmail.com",
    "website": "http://www.mahikufarmersmarket.com"
  },
  {
    "name": "Mahiku Farmers' Market at Momilani Community Center",
    "streetAddress": "715 Hoomoana St",
    "locationInfo": "Corner of Hoomoana & Komo Mai Dr",
    "latitude": 21.408970034000447,
    "longitude": -157.96024986999973,
    "island": "Oahu",
    "city": "Pearl City",
    "zipcode": 96782,
    "contact": "Sonny Doung",
    "phone": "(808) 225-4002",
    "email": "sonnydoung@hotmail.com",
    "website": "http://www.mahikufarmersmarket.com"
  },
  {
    "name": "Makawao Farmers' Market (Baldwin)",
    "streetAddress": "3654 Baldwin Avenue",
    "locationInfo": "",
    "latitude": "",
    "longitude": "",
    "island": "Maui",
    "city": "Makawao",
    "zipcode": "",
    "contact": "",
    "phone": "",
    "email": "",
    "website": ""
  },
  {
    "name": "Makawao Farmers' Market (Olinda)",
    "streetAddress": "200 Olinda Rd.",
    "locationInfo": "Po'okela Church on Olinda Road",
    "latitude": 20.849390600000447,
    "longitude": -156.30839892799975,
    "island": "Maui",
    "city": "Makawao",
    "zipcode": 96768,
    "contact": "Debbie",
    "phone": "(808) 419-1570",
    "email": "",
    "website": "http://makawaofarmersmarket.org/"
  },
  {
    "name": "Makeke Kapolei",
    "streetAddress": "",
    "locationInfo": "Kapolei High School",
    "latitude": 21.334220008000443,
    "longitude": -158.08191927499973,
    "island": "Oahu",
    "city": "Kapolei",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 697-3599",
    "email": "",
    "website": ""
  },
  {
    "name": "Makiki District Park (People's Open Market)",
    "streetAddress": "1527 Keeaumoku Street",
    "locationInfo": "",
    "latitude": 21.30367101400043,
    "longitude": -157.83730940699974,
    "island": "Oahu",
    "city": "Honolulu",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 522-7088",
    "email": "",
    "website": ""
  },
  {
    "name": "Makiki Local Grown Farmers' Market at St. Clement's Church",
    "streetAddress": "1515 Wilder Avenue",
    "locationInfo": "Parking on Wilder after 5:30 p.m",
    "latitude": 21.30376089200047,
    "longitude": -157.83456927999973,
    "island": "Oahu",
    "city": "Honolulu",
    "zipcode": "",
    "contact": "George Lee",
    "phone": "(808) 735-4550",
    "email": "georgelee2468@gmail.com",
    "website": ""
  },
  {
    "name": "Maku'u Farmer's Market",
    "streetAddress": "",
    "locationInfo": "Highway 130, between Keaau and Pahoa",
    "latitude": "",
    "longitude": "",
    "island": "Hawaii",
    "city": "Pahoa",
    "zipcode": 96778,
    "contact": "",
    "phone": "(808) 965-1441",
    "email": "kekahuna@localnet.com",
    "website": ""
  },
  {
    "name": "Mamo Street Market",
    "streetAddress": "",
    "locationInfo": "Mamo Parking Lot",
    "latitude": "",
    "longitude": "",
    "island": "Hawaii",
    "city": "Hilo",
    "zipcode": "",
    "contact": "",
    "phone": "",
    "email": "",
    "website": ""
  },
  {
    "name": "Manoa Marketplace",
    "streetAddress": "2752 Woodlawn Drive",
    "locationInfo": "",
    "latitude": 21.307510418000447,
    "longitude": -157.80973989899974,
    "island": "Oahu",
    "city": "Honolulu",
    "zipcode": 96822,
    "contact": "",
    "phone": "(808) 847-0494",
    "email": "",
    "website": ""
  },
  {
    "name": "Manoa Valley District Park (People's Open Market)",
    "streetAddress": "2721 Kaaipu Avenue",
    "locationInfo": "",
    "latitude": 21.313510263000467,
    "longitude": -157.81033479899975,
    "island": "Oahu",
    "city": "Honolulu",
    "zipcode": 96822,
    "contact": "",
    "phone": "(808) 522-7088",
    "email": "",
    "website": ""
  },
  {
    "name": "Maui Mall Farmers' Market & Craft Fair",
    "streetAddress": "70 East Kaahumanu Ave",
    "locationInfo": "",
    "latitude": 20.892510160000427,
    "longitude": -156.46427968799975,
    "island": "Maui",
    "city": "Kahului",
    "zipcode": 96732,
    "contact": "Cynda Hearn",
    "phone": "(808) 871-1307",
    "email": "",
    "website": ""
  },
  {
    "name": "Maui Open Market, Maui Tropical Plantation",
    "streetAddress": "1670 Honoapiilani Hwy",
    "locationInfo": "",
    "latitude": 20.85027094500043,
    "longitude": -156.50449895199975,
    "island": "Maui",
    "city": "Wailuku",
    "zipcode": 96793,
    "contact": "",
    "phone": "(808) 244-7643",
    "email": "",
    "website": ""
  },
  {
    "name": "Maui Swap Meet",
    "streetAddress": "310 Ka'ahumanu Avenue",
    "locationInfo": "Maui Community College (lot nearest to Kahului Beach Road)",
    "latitude": 20.88888047000046,
    "longitude": -156.47681997699974,
    "island": "Maui",
    "city": "Kahului",
    "zipcode": 96732,
    "contact": "",
    "phone": "(808) 877-3100",
    "email": "",
    "website": ""
  },
  {
    "name": "Merchant Street Market",
    "streetAddress": "841 Bishop Street",
    "locationInfo": "2nd and 4th Tuesday of each month",
    "latitude": 21.3078307530004,
    "longitude": -157.862429162999,
    "island": "Oahu",
    "city": "Honolulu",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 545-4477",
    "email": "dpcinfo@isleconcierge.com",
    "website": ""
  },
  {
    "name": "Mililani District Park (People's Open Market)",
    "streetAddress": "94-1150 Lanikuhana Avenue",
    "locationInfo": "",
    "latitude": 21.440746715000444,
    "longitude": -158.01797200199974,
    "island": "Oahu",
    "city": "Mililani",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 522-7088",
    "email": "",
    "website": ""
  },
  {
    "name": "Molokai Saturday Market",
    "streetAddress": "40 Ala Malama Street",
    "locationInfo": "Ala Malama Street at the Thomas Trade Building, located between Bank of Hawaiâ€˜i and American Savings Bank.",
    "latitude": 21.09017112200047,
    "longitude": -157.02199661599974,
    "island": "Molokai",
    "city": "Kaunakakai",
    "zipcode": 96748,
    "contact": "",
    "phone": "",
    "email": "",
    "website": ""
  },
  {
    "name": "Mother Waldron Park (People's Open Market)",
    "streetAddress": "525 Coral Street",
    "locationInfo": "",
    "latitude": 21.300129225000433,
    "longitude": -157.85790736199974,
    "island": "Oahu",
    "city": "Honolulu",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 522-7088",
    "email": "",
    "website": ""
  },
  {
    "name": "North Shore Country Market",
    "streetAddress": "",
    "locationInfo": "Sunset Beach Elementary School",
    "latitude": 21.58948073400046,
    "longitude": -158.10290913599974,
    "island": "Oahu",
    "city": "Haleiwa",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 237-8248",
    "email": "",
    "website": "http://www.northshorecountrymarket.com"
  },
  {
    "name": "Nuuanu Farmers Market",
    "streetAddress": "2313 Nuuanu Avenue",
    "locationInfo": "Honolulu Central Seventh Day Adventist Church",
    "latitude": 21.326480443000435,
    "longitude": -157.84731928399975,
    "island": "Oahu",
    "city": "Honolulu",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 282-2276",
    "email": "nuuanumarket@gmail.com",
    "website": ""
  },
  {
    "name": "Old Stadium Park (People's Open Market)",
    "streetAddress": "2237 South King Street",
    "locationInfo": "",
    "latitude": 21.293791309000426,
    "longitude": -157.82719811599975,
    "island": "Oahu",
    "city": "Honolulu",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 522-7088",
    "email": "",
    "website": ""
  },
  {
    "name": "Ono Organic Farms Farmers' Market",
    "streetAddress": "149 Hana Highway",
    "locationInfo": "Old gas station, Hasegawa General Store - Hana Hwy.",
    "latitude": 20.80699101600044,
    "longitude": -156.09087728399973,
    "island": "Maui",
    "city": "Hana",
    "zipcode": 96713,
    "contact": "",
    "phone": "(808) 248-7779",
    "email": "",
    "website": ""
  },
  {
    "name": "Paia's One Love Farmers Market",
    "streetAddress": "381 Baldwin Ave",
    "locationInfo": "Historical Paia train depot",
    "latitude": 20.906238207000456,
    "longitude": -156.37416925199975,
    "island": "Maui",
    "city": "Paia",
    "zipcode": 96799,
    "contact": "",
    "phone": "",
    "email": "",
    "website": "http://www.lahainaproduce.com"
  },
  {
    "name": "Palolo Valley District Park (People's Open Market)",
    "streetAddress": "2007 Palolo Avenue",
    "locationInfo": "",
    "latitude": 21.3006105510004,
    "longitude": -157.795998931999,
    "island": "Oahu",
    "city": "Honolulu",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 522-7088",
    "email": "",
    "website": ""
  },
  {
    "name": "Panaewa Hawaiian Home Lands Farmers' Market",
    "streetAddress": "",
    "locationInfo": "Corner of Puainako and Ohuohu., On the sidewalk of Hilo WalMart",
    "latitude": "",
    "longitude": "",
    "island": "Hawaii",
    "city": "Hilo",
    "zipcode": "",
    "contact": "Jerry",
    "phone": "(808) 959-0488",
    "email": "",
    "website": ""
  },
  {
    "name": "Pokai Bay Beach Park (People's Open Market)",
    "streetAddress": "85-037 Pokai Bay Road",
    "locationInfo": "",
    "latitude": 21.44185853600044,
    "longitude": -158.18862608699973,
    "island": "Oahu",
    "city": "Waianae",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 522-7088",
    "email": "",
    "website": ""
  },
  {
    "name": "Queen Kapiolani Park (People's Open Market)",
    "streetAddress": "",
    "locationInfo": "Monsarrat and Paki Street",
    "latitude": 21.304850435000446,
    "longitude": -157.85774940299973,
    "island": "Oahu",
    "city": "Honolulu",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 522-7088",
    "email": "",
    "website": ""
  },
  {
    "name": "Queen's Medical Center",
    "streetAddress": "1301 Punchbowl Street",
    "locationInfo": "First Wednesdays",
    "latitude": 21.307250002000444,
    "longitude": -157.85527925099973,
    "island": "Oahu",
    "city": "Honolulu",
    "zipcode": "",
    "contact": "",
    "phone": "",
    "email": "",
    "website": ""
  },
  {
    "name": "Restaurant Row Farmers' Market",
    "streetAddress": "500 Ala Moana Boulevard",
    "locationInfo": "",
    "latitude": "",
    "longitude": "",
    "island": "Oahu",
    "city": "Honolulu",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 537-5158",
    "email": "wfpinfo@isleconcierge.com",
    "website": ""
  },
  {
    "name": "Royal Kunia Park-n-Ride (People's Open Market)",
    "streetAddress": "",
    "locationInfo": "Kupuna Lp / Kupohi Stree",
    "latitude": 21.385861307000425,
    "longitude": -158.00350991899975,
    "island": "Oahu",
    "city": "Waipahu",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 522-7088",
    "email": "",
    "website": ""
  },
  {
    "name": "Salt Lake Municipal Lot  (People's Open Market)",
    "streetAddress": "5337 Likini Street",
    "locationInfo": "",
    "latitude": 21.34594295700043,
    "longitude": -157.90491127999974,
    "island": "Oahu",
    "city": "Honolulu",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 522-7088",
    "email": "",
    "website": ""
  },
  {
    "name": "South Kona Fruit Stand",
    "streetAddress": "84-4770 Mamalahoa Hwy",
    "locationInfo": "Near the old Higashi Store, between mile marker 103 &104",
    "latitude": "",
    "longitude": "",
    "island": "Hawaii",
    "city": "Captain Cook",
    "zipcode": "",
    "contact": "Beth",
    "phone": "(808) 328-8547",
    "email": "",
    "website": ""
  },
  {
    "name": "The Kailua Thursday Night Farmers Market",
    "streetAddress": "",
    "locationInfo": "Kailua Road - Kailua Parking Garage (behind Longs)",
    "latitude": 21.396571048000453,
    "longitude": -157.74006959799974,
    "island": "Oahu",
    "city": "Kailua",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 848-2074",
    "email": "",
    "website": "http://www.hfbf.org"
  },
  {
    "name": "The Market Place",
    "streetAddress": "",
    "locationInfo": "Across from the Hilo Farmer's Market",
    "latitude": "",
    "longitude": "",
    "island": "Hawaii",
    "city": "",
    "zipcode": "",
    "contact": "Keith",
    "phone": "(808) 933-1000",
    "email": "",
    "website": "www.hilofarmersmarket.com"
  },
  {
    "name": "The Maui's Fresh Produce Farmer's Market at Queen Ka'ahumanu Shopping Center",
    "streetAddress": "275 W. Ka'ahumanu Ave",
    "locationInfo": "Center stage area",
    "latitude": 20.881122485000446,
    "longitude": -156.47201774299972,
    "island": "Maui",
    "city": "Kahului",
    "zipcode": 96732,
    "contact": "",
    "phone": "(808) 877-4325",
    "email": "",
    "website": ""
  },
  {
    "name": "The Mililani Sunday Farmers' Market at Mililani High School",
    "streetAddress": "95-1200 Meheula Parkway",
    "locationInfo": "Mililani High School Parking Lot",
    "latitude": 21.452906795000445,
    "longitude": -158.00846980399973,
    "island": "Oahu",
    "city": "Mililani",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 848-2074",
    "email": "",
    "website": "http://www.hfbf.org"
  },
  {
    "name": "The Saturday Farmers' Market at Kapiolani Community College Campus",
    "streetAddress": "4303 Diamond Head Road",
    "locationInfo": "Kapiolani Community College Campus",
    "latitude": 21.26960032800048,
    "longitude": -157.80306933599974,
    "island": "Oahu",
    "city": "Honolulu",
    "zipcode": 96816,
    "contact": "",
    "phone": "(808) 848-2074",
    "email": "",
    "website": "http://www.hfbf.org"
  },
  {
    "name": "The South Kona Green Market",
    "streetAddress": "",
    "locationInfo": "Amy Greenwell Ethnobotanical Garden field in Captain Cook",
    "latitude": 19.496937200000446,
    "longitude": -155.92166908399975,
    "island": "Hawaii",
    "city": "Captain Cook",
    "zipcode": "",
    "contact": "Esta Feedora",
    "phone": "(808) 328-2400",
    "email": "",
    "website": "http://www.skgm.org"
  },
  {
    "name": "Under the Banyan's Farmers' Market",
    "streetAddress": "",
    "locationInfo": "",
    "latitude": "",
    "longitude": "",
    "island": "Hawaii",
    "city": "Hawi",
    "zipcode": "",
    "contact": "",
    "phone": "",
    "email": "",
    "website": ""
  },
  {
    "name": "Upcountry Farmers' Market at Pukalani Longs Drugs at Kulamalu",
    "streetAddress": "55 Kiopaa St",
    "locationInfo": "Pukalani Longs Drugs at Kulamalu",
    "latitude": 20.822089506000452,
    "longitude": -156.33009308199973,
    "island": "Maui",
    "city": "Makawao",
    "zipcode": 96768,
    "contact": "",
    "phone": "",
    "email": "info@upcountryfarmersmarket.com",
    "website": ""
  },
  {
    "name": "Vidinha Stadium (Sunshine Markets)",
    "streetAddress": "",
    "locationInfo": "Hoolako Road",
    "latitude": 21.967180168000425,
    "longitude": -159.36190806199974,
    "island": "Kauai",
    "city": "Lihue",
    "zipcode": "",
    "contact": "Cora Asuncion",
    "phone": "(808) 742-1834",
    "email": "",
    "website": ""
  },
  {
    "name": "Village Farmers' Market",
    "streetAddress": "",
    "locationInfo": "Across from Hale Halawai",
    "latitude": "",
    "longitude": "",
    "island": "Hawaii",
    "city": "Kailua-Kona",
    "zipcode": "",
    "contact": "",
    "phone": "",
    "email": "",
    "website": ""
  },
  {
    "name": "Volcano Farmers' Market",
    "streetAddress": "1000 Wright Road",
    "locationInfo": "Cooper Center",
    "latitude": "",
    "longitude": "",
    "island": "Hawaii",
    "city": "Volcano",
    "zipcode": "",
    "contact": "Betsy Mitchell",
    "phone": "(808) 967-7209",
    "email": "",
    "website": ""
  },
  {
    "name": "Wahiawa District Park (People's Open Market)",
    "streetAddress": "",
    "locationInfo": "N. Cane & California Avenue",
    "latitude": 21.304850435000446,
    "longitude": -157.85774940299973,
    "island": "Oahu",
    "city": "Wahiawa",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 522-7088",
    "email": "",
    "website": ""
  },
  {
    "name": "Waialua Farmers' Market",
    "streetAddress": "",
    "locationInfo": "Waialua Sugar Mill",
    "latitude": 21.304850435000446,
    "longitude": -157.85774940299973,
    "island": "Oahu",
    "city": "Waialua",
    "zipcode": "",
    "contact": "Edith Ramiscal",
    "phone": "",
    "email": "info@sugarmillhawaii.com",
    "website": ""
  },
  {
    "name": "Waianae Farmers' Market (sponsored by Waianae Coast Comprehensive Center)",
    "streetAddress": "85-251 Farrington Highway",
    "locationInfo": "Waianae High School, Cafeteria Lanai",
    "latitude": 21.455940520000468,
    "longitude": -158.19946945199973,
    "island": "Oahu",
    "city": "Waianae",
    "zipcode": "",
    "contact": "Desiree",
    "phone": "(808) 388-7386",
    "email": "waianaefarmersmarket@wcchc.com",
    "website": "http://www.waianaefarmersmarket.org"
  },
  {
    "name": "Waiau District Park (People's Open Market)",
    "streetAddress": "",
    "locationInfo": "Komo Mai Drive, Pearl City",
    "latitude": 21.393800202000477,
    "longitude": -157.96977976199975,
    "island": "Oahu",
    "city": "Pearl City",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 522-7088",
    "email": "",
    "website": ""
  },
  {
    "name": "Waikele Community Park (People's Open Market)",
    "streetAddress": "94-870 Lumiaina Street",
    "locationInfo": "",
    "latitude": 21.40006058600045,
    "longitude": -158.00463924399975,
    "island": "Oahu",
    "city": "Waipahu",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 522-7088",
    "email": "",
    "website": ""
  },
  {
    "name": "Waikiki Farmers' Market",
    "streetAddress": "",
    "locationInfo": "Waikiki Community Center's Parking Lot",
    "latitude": 21.30485044,
    "longitude": 157.857749402999,
    "island": "Oahu",
    "city": "Honolulu",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 923-1802",
    "email": "",
    "website": ""
  },
  {
    "name": "Waikoloa Village Farmers Market",
    "streetAddress": "68-3625 Paniolo Ave.",
    "locationInfo": "Waikoloa Community Church Parking Lot",
    "latitude": 19.9427347680004,
    "longitude": -155.79099041899974,
    "island": "Hawaii",
    "city": "Waikoloa",
    "zipcode": "",
    "contact": "",
    "phone": "",
    "email": "",
    "website": ""
  },
  {
    "name": "Waimanalo Beach Park (People's Open Market)",
    "streetAddress": "41-741 Kalanianaole Highway",
    "locationInfo": "",
    "latitude": 21.329640001000428,
    "longitude": -157.69172889999973,
    "island": "Oahu",
    "city": "Waimanalo",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 522-7088",
    "email": "",
    "website": ""
  },
  {
    "name": "Waimea Town Market",
    "streetAddress": "",
    "locationInfo": "Parker School\nBehind Paniolo Country Inn",
    "latitude": "",
    "longitude": "",
    "island": "Hawaii",
    "city": "",
    "zipcode": "",
    "contact": "",
    "phone": "",
    "email": "",
    "website": ""
  },
  {
    "name": "Waipahu District Park (People's Open Market)",
    "streetAddress": "94-230 Paiwa Stree",
    "locationInfo": "",
    "latitude": 21.38803075800047,
    "longitude": -157.99936985699975,
    "island": "Oahu",
    "city": "Waipahu",
    "zipcode": "",
    "contact": "",
    "phone": "(808) 522-7088",
    "email": "",
    "website": ""
  },
  {
    "name": "Ward Center",
    "streetAddress": "",
    "locationInfo": "Parking lot across from Ward 16 Theatres, Corner of Auahi & Kamakee St.",
    "latitude": 21.304850435000446,
    "longitude": -157.85774940299973,
    "island": "Oahu",
    "city": "Honolulu",
    "zipcode": "",
    "contact": "",
    "phone": "",
    "email": "",
    "website": "http://www.wardcenters.com"
  },
  {
    "name": "West Kauai Agricultural Association",
    "streetAddress": "",
    "locationInfo": "Poipu Road and Cane Haul Road",
    "latitude": "",
    "longitude": "",
    "island": "Kauai",
    "city": "Poipu",
    "zipcode": "",
    "contact": "",
    "phone": "",
    "email": "",
    "website": ""
  },
  {
    "name": "Windward Mall",
    "streetAddress": "46-056 Kamehameha Highway",
    "locationInfo": "Fronting Macy's",
    "latitude": 21.42064035000044,
    "longitude": -157.80338967099974,
    "island": "Oahu",
    "city": "Kaneohe",
    "zipcode": "",
    "contact": "",
    "phone": "",
    "email": "",
    "website": "http://www.windwardmall.com/event/farmers-market-every-Wednesday"
  }
];


if (FarmersMarket.find().count() === 0){
  _.each(farmersmarketSeed, function(farmersmarkets){
    FarmersMarket.insert(farmersmarkets);
  });
}